# Generated by Django 3.1.3 on 2020-11-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Аллерген',
                'verbose_name_plural': 'Аллергены',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('nutritional_value', models.IntegerField(default=0, verbose_name='Пищевая ценность')),
                ('picture', models.ImageField(default=None, upload_to='static/menu/img', verbose_name='Картинка')),
                ('category', models.CharField(choices=[('Фуршетное меню', 'Фуршетное меню'), ('Холодные закуски', 'Холодные закуски'), ('Салаты', 'Салаты'), ('Горячее', 'Горячее'), ('Гарниры', 'Гарниры'), ('Выпечка', 'Выпечка'), ('Напитки', 'Напитки')], default='Фуршетное меню', max_length=100, verbose_name='Категория')),
                ('allergens', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.allergen')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Меню ресторана',
            },
        ),
    ]
