# Generated by Django 3.1.3 on 2020-11-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='id',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='allergens',
        ),
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(default=None, to='menu.Allergen'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='nutritional_value',
            field=models.IntegerField(default=0, help_text='В ккал/г', verbose_name='Пищевая ценность'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(default=0, help_text='В рублях', verbose_name='Цена'),
        ),
    ]
