# Generated by Django 3.1.3 on 2020-11-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20201119_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
