# Generated by Django 3.1.3 on 2020-11-23 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201119_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(default=0, error_messages={'invalid': 'Дурак?'}, help_text='В рублях', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Цена'),
        ),
    ]
