# Generated by Django 3.1.3 on 2020-11-23 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20201123_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='nutritional_value',
            field=models.IntegerField(default=0, error_messages={'empty_value': 'Значение не может быть пустым.', 'min_value': 'Введите значение больше нуля.', 'required': 'Это обязательное поле.'}, help_text='В ккал/г', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Пищевая ценность'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(default=0, error_messages={'empty_value': 'Значение не может быть пустым.', 'min_value': 'Введите значение больше нуля.', 'required': 'Это обязательное поле.'}, help_text='В рублях', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(default='', error_messages={'required': 'custom required message'}, max_length=100, verbose_name='Название'),
        ),
    ]
