# Generated by Django 3.1.3 on 2020-11-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20201123_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(blank=True, default=None, related_name='allergens', to='menu.Allergen'),
        ),
    ]
