# Generated by Django 3.1.3 on 2020-11-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20201124_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='allergens', to='menu.Allergen'),
        ),
    ]
