# Generated by Django 3.1.3 on 2020-11-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20201124_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(blank=True, default=None, related_name='allergens', to='menu.Allergen'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Закуски', 'Закуски'), ('Салаты', 'Салаты'), ('Супы', 'Супы'), ('Мясо', 'Мясо'), ('Пицца', 'Пицца'), ('Десерты', 'Десерты')], default=None, max_length=100, verbose_name='Категория'),
        ),
    ]
